name: My First Workflow

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
   
    steps:
     - name: Code Checkout Repo 
       uses: actions/checkout@v5 

     

     - name: Test Application Code
       run: ls -l

     